//
// Created by onething on 2018/4/13.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_andy_andydemo_ndk_myJNI */

#ifndef _Included_com_example_andy_andydemo_ndk_myJNI
#define _Included_com_example_andy_andydemo_ndk_myJNI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_andy_andydemo_ndk_myJNI
 * Method:    sayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_andy_andydemo_ndk_myJNI_sayHello
        (JNIEnv *env, jclass jobj){

    return (*env)->NewStringUTF(env,"JNI hahahahahahahaha");

}

/*
 * Class:     com_example_andy_andydemo_ndk_myJNI
 * Method:    plus
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jint JNICALL Java_com_example_andy_andydemo_ndk_myJNI_plus
        (JNIEnv *env, jclass jobj, jint x, jint y)
{

    return x + y;

}


#ifdef __cplusplus
}
#endif
#endif
