//
// Created by onething on 2018/5/2.
//

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_andy_andydemo_ndk_NdkUtils */

#ifndef _Included_com_example_andy_andydemo_ndk_NdkUtils
#define _Included_com_example_andy_andydemo_ndk_NdkUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_andy_andydemo_ndk_NdkUtils
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_andy_andydemo_ndk_NdkUtils_getStringFromC
        (JNIEnv *env, jclass jobj){
    return (*env)->NewStringUTF(env,"hello, my name is JNI demo by NDK");
}

#ifdef __cplusplus
}
#endif
#endif
